/**
 * ⚠️ This is a hardcoded map of fiscal year starts for each jurisdiction.
 */

import {
  EJurisdictionCode,
  type UJurisdictionCode,
} from '@/shared/utils/api/Api';

export type IFiscalYearStart = {
  month: number;
  day: number;
};

export const FISCAL_YEAR_STARTS: Record<UJurisdictionCode, IFiscalYearStart> = {
  [EJurisdictionCode.AD]: { month: 1, day: 1 },
  [EJurisdictionCode.AE]: { month: 1, day: 1 },
  [EJurisdictionCode.AR]: { month: 1, day: 1 },
  [EJurisdictionCode.AT]: { month: 1, day: 1 },
  [EJurisdictionCode.AU]: { month: 7, day: 1 },
  [EJurisdictionCode.BD]: { month: 7, day: 1 },
  [EJurisdictionCode.BE]: { month: 1, day: 1 },
  [EJurisdictionCode.BR]: { month: 1, day: 1 },
  [EJurisdictionCode.CA]: { month: 1, day: 1 },
  [EJurisdictionCode.CH]: { month: 1, day: 1 },
  [EJurisdictionCode.CI]: { month: 1, day: 1 },
  [EJurisdictionCode.CL]: { month: 1, day: 1 },
  [EJurisdictionCode.CM]: { month: 1, day: 1 },
  [EJurisdictionCode.CN]: { month: 1, day: 1 },
  [EJurisdictionCode.CO]: { month: 1, day: 1 },
  [EJurisdictionCode.CY]: { month: 1, day: 1 },
  [EJurisdictionCode.CZ]: { month: 1, day: 1 },
  [EJurisdictionCode.DE]: { month: 1, day: 1 },
  [EJurisdictionCode.DK]: { month: 1, day: 1 },
  [EJurisdictionCode.DZ]: { month: 1, day: 1 },
  [EJurisdictionCode.EE]: { month: 1, day: 1 },
  [EJurisdictionCode.EG]: { month: 7, day: 1 },
  [EJurisdictionCode.ES]: { month: 1, day: 1 },
  [EJurisdictionCode.FI]: { month: 1, day: 1 },
  [EJurisdictionCode.FR]: { month: 1, day: 1 },
  [EJurisdictionCode.GB]: { month: 4, day: 1 },
  [EJurisdictionCode.GH]: { month: 1, day: 1 },
  [EJurisdictionCode.GR]: { month: 1, day: 1 },
  [EJurisdictionCode.HK]: { month: 4, day: 1 },
  [EJurisdictionCode.HR]: { month: 1, day: 1 },
  [EJurisdictionCode.HU]: { month: 1, day: 1 },
  [EJurisdictionCode.ID]: { month: 1, day: 1 },
  [EJurisdictionCode.IE]: { month: 1, day: 1 },
  [EJurisdictionCode.IL]: { month: 1, day: 1 },
  [EJurisdictionCode.IN]: { month: 4, day: 1 },
  [EJurisdictionCode.IT]: { month: 1, day: 1 },
  [EJurisdictionCode.JP]: { month: 4, day: 1 },
  [EJurisdictionCode.KE]: { month: 7, day: 1 },
  [EJurisdictionCode.KR]: { month: 1, day: 1 },
  [EJurisdictionCode.LT]: { month: 1, day: 1 },
  [EJurisdictionCode.LU]: { month: 1, day: 1 },
  [EJurisdictionCode.LV]: { month: 1, day: 1 },
  [EJurisdictionCode.MA]: { month: 1, day: 1 },
  [EJurisdictionCode.MC]: { month: 1, day: 1 },
  [EJurisdictionCode.MT]: { month: 1, day: 1 },
  [EJurisdictionCode.MX]: { month: 1, day: 1 },
  [EJurisdictionCode.MY]: { month: 1, day: 1 },
  [EJurisdictionCode.NG]: { month: 1, day: 1 },
  [EJurisdictionCode.NL]: { month: 1, day: 1 },
  [EJurisdictionCode.NO]: { month: 1, day: 1 },
  [EJurisdictionCode.NZ]: { month: 4, day: 1 },
  [EJurisdictionCode.PE]: { month: 1, day: 1 },
  [EJurisdictionCode.PH]: { month: 1, day: 1 },
  [EJurisdictionCode.PK]: { month: 7, day: 1 },
  [EJurisdictionCode.PL]: { month: 1, day: 1 },
  [EJurisdictionCode.PT]: { month: 1, day: 1 },
  [EJurisdictionCode.RO]: { month: 1, day: 1 },
  [EJurisdictionCode.RU]: { month: 1, day: 1 },
  [EJurisdictionCode.SA]: { month: 1, day: 1 },
  [EJurisdictionCode.SE]: { month: 1, day: 1 },
  [EJurisdictionCode.SG]: { month: 1, day: 1 },
  [EJurisdictionCode.SI]: { month: 1, day: 1 },
  [EJurisdictionCode.SK]: { month: 1, day: 1 },
  [EJurisdictionCode.SM]: { month: 1, day: 1 },
  [EJurisdictionCode.SN]: { month: 1, day: 1 },
  [EJurisdictionCode.TH]: { month: 1, day: 1 },
  [EJurisdictionCode.TR]: { month: 1, day: 1 },
  [EJurisdictionCode.TW]: { month: 1, day: 1 },
  [EJurisdictionCode.TZ]: { month: 7, day: 1 },
  [EJurisdictionCode.UA]: { month: 1, day: 1 },
  [EJurisdictionCode.UG]: { month: 7, day: 1 },
  [EJurisdictionCode.US]: { month: 1, day: 1 },
  [EJurisdictionCode.VA]: { month: 1, day: 1 },
  [EJurisdictionCode.VN]: { month: 1, day: 1 },
  [EJurisdictionCode.ZA]: { month: 3, day: 1 },
};
